### PR TITLE
Meetings without Attendance

### LINKED ISSUE #88: Meetings can be marked as no attendance taken/free attendance
e.g. the first few meetings where attendance isn't taken, shouldn't count as missed attendances

### PR DESCRIPTION
**Pull request by Apexal**
Closes #88 

Screenshot 2023-02-05 at 8 38 49 AM

### CODE REVIEW

**Review by bnidevs — APPROVED** [review]

**Comment by bnidevs** [comment]
can we mark ongoing meetings as ongoing, then mark past meetings as either attended, not attended or attendance not taken?

**Comment by Apexal** [comment]
I'm not following, what do you mean?

**Comment by bnidevs** [comment]
differentiate between past and ongoing meetings (starts_at < now < ends_at)

**Comment by bnidevs** [comment]
eg, it's possible there's a meeting that's currently happening, but the attendance window is not closed yet, and the user hasn't attended *yet* so it will say "ONGOING" just in case they can still make it or haven't gotten the attendance yet

**Comment by Apexal** [comment]
> eg, it's possible there's a meeting that's currently happening, but the attendance window is not closed yet, and the user hasn't attended _yet_ so it will say "ONGOING" just in case they can still make it or haven't gotten the attendance yet

I updated the places it is displayed to display "ongoing" in that event!

**Comment by bnidevs** [comment]
thanks frank

**Pull request merged**
